<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Undangan Samuel & Oliv</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Poppins:wght@400;600&display=swap" rel="stylesheet">
  <style>
    body {
      font-family: 'Poppins', sans-serif;
      background: url('https://www.transparenttextures.com/patterns/cream-pixels.png');
      background-color: #fff0f3;
      scroll-behavior: smooth;
    }
    .hero {
      height: 100vh;
      background: linear-gradient(rgba(255,255,255,0.7), rgba(255,255,255,0.7)), 
                  url('image.png') center/cover no-repeat;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      text-align: center;
    }
    .hero h1 {
      font-family: 'Great Vibes', cursive;
      font-size: 3.5rem;
      color: #b76e79;
      margin-bottom: 0.5rem;
    }
    .hero p {
      font-size: 1.3rem;
      color: #6c757d;
      margin-bottom: 2rem;
    }
    .btn-rose {
      background-color: #b76e79;
      color: white;
      border: none;
    }
    .btn-rose:hover {
      background-color: #9f5a64;
    }
    .section {
      padding: 60px 0;
    }
    #opening {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100vh;
      background: linear-gradient(rgba(255,255,255,0.7), rgba(255,255,255,0.7)), url('image.png') center/cover no-repeat;
      z-index: 9999;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-direction: column;
      transition: 1s;
    }
    .countdown {
      font-size: 2rem;
      color: #b76e79;
      margin-top: 20px;
    }
    footer {
      background: #f8d7da;
      padding: 20px;
      font-size: 0.9rem;
    }
    .fade-in {
      animation: fadeIn 2s ease forwards;
    }
    @keyframes fadeIn {
      0% {opacity: 0;}
      100% {opacity: 1;}
    }
    audio {
      display: none;
    }

    /* Styling untuk Form */
.card {
  background-color: #fff;
  border-radius: 15px;
  padding: 20px;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
}

.card .form-control-lg {
  border-radius: 10px;
}

.card .btn-rose {
  background-color: #b76e79;
  color: white;
  border-radius: 10px;
  font-size: 1.1rem;
  padding: 12px;
}

.card .btn-rose:hover {
  background-color: #9f5a64;
  transition: background-color 0.3s ease;
}

/* Animasi untuk alasan tidak hadir */
#reason-container {
  transition: all 0.5s ease-in-out;
}

  </style>
</head>

<body>

<!-- Opening Screen -->
<div id="opening">
  <h2 class="text-muted mb-3">The Wedding Of</h2>
  <h1>Samuel & Oliv</h1>
  <button class="btn btn-rose mt-4" onclick="openInvitation()">Buka Undangan</button>
</div>

<!-- Background music
<audio id="bgm" loop>
  <source src="https://www.bensound.com/bensound-music/bensound-love.mp3" type="audio/mp3">
</audio> -->

<!-- Main Content -->
<div id="main-content" style="display:none;" class="fade-in">

  <!-- Hero Section -->
  <section class="hero" id="home">
    <div class="container">
      <p id="kepada-text" class="text-muted"></p>
      <p>The Wedding Of</p>
      <h1>Samuel & Oliv</h1>
      <p>30 April 2025</p>
      <a href="#acara" class="btn btn-rose mt-4">Lihat Detail Acara</a>
    </div>
  </section>

  <!-- Countdown Section -->
  <section class="section bg-light text-center">
    <div class="container">
      <h2 class="mb-4">Menuju Hari Bahagia</h2>
      <div id="countdown" class="countdown"></div>
    </div>
  </section>

  <!-- Detail Acara Section -->
  <!-- Detail Acara Section -->
<section id="acara" class="section text-center" style="padding: 50px 0; background: linear-gradient(135deg, #ffafcc, #ff7b9d); border-radius: 20px; box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);">
    <div class="container">
      <h2 class="mb-5" style="font-family: 'Poppins', sans-serif; font-weight: bold; font-size: 2.5rem; color: white;">Detail Acara</h2>
      
      <div class="row">
        <div class="col-md-6 mb-4">
          <div class="card shadow-lg border-0 rounded-lg" style="background-color: #fff; padding: 20px;">
            <h4 class="mb-3" style="font-family: 'Poppins', sans-serif; font-weight: 600; font-size: 1.8rem;">Akad Nikah</h4>
            <p style="font-size: 1.25rem; color: #ff7b9d;">10:00 WIB</p>
            <p style="font-size: 1.25rem; color: #888;">Ballroom A</p>
            <i class="bi bi-heart-fill" style="font-size: 3rem; color: #ff7b9d;"></i>
          </div>
        </div>
        
        <div class="col-md-6 mb-4">
          <div class="card shadow-lg border-0 rounded-lg" style="background-color: #fff; padding: 20px;">
            <h4 class="mb-3" style="font-family: 'Poppins', sans-serif; font-weight: 600; font-size: 1.8rem;">Resepsi</h4>
            <p style="font-size: 1.25rem; color: #ff7b9d;">18:00 WIB</p>
            <p style="font-size: 1.25rem; color: #888;">Ballroom B</p>
            <i class="bi bi-balloon-heart-fill" style="font-size: 3rem; color: #ff7b9d;"></i>
          </div>
        </div>
      </div>
      
      <p class="mt-4" style="font-size: 1.25rem; color: white;"><strong>Lokasi:</strong> Hotel Grand Wedding, Jakarta</p>
      <a href="https://goo.gl/maps/xxxx" target="_blank" class="btn btn-outline-light btn-lg mt-3 px-4 py-2" style="border-radius: 25px; border: 2px solid #fff; color: #fff; font-size: 1.2rem;">
        Lihat Lokasi
      </a>
    </div>
  </section>
  

  <!-- RSVP Form Section -->
<section class="section bg-light text-center">
    <div class="container">
      <h2 class="mb-4">Konfirmasi Kehadiran</h2>
      <p>Mohon isi form di bawah ini untuk mengonfirmasi kehadiran Anda.</p>
      
      <div class="card p-4 shadow-lg mx-auto" style="max-width: 600px; border-radius: 15px;">
        <form id="rsvp-form">
          <div class="mb-3">
            <label for="name" class="form-label">Nama Lengkap</label>
            <input type="text" id="name" class="form-control form-control-lg" placeholder="Masukkan Nama Anda" required>
          </div>
          
          <div class="mb-3">
            <label for="email" class="form-label">Email (Opsional)</label>
            <input type="email" id="email" class="form-control form-control-lg" placeholder="Masukkan Email Anda (opsional)">
          </div>
          
          <div class="mb-3">
            <label class="form-label">Apakah Anda Akan Hadir?</label>
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="attending" id="attend-yes" value="Yes" checked>
              <label class="form-check-label" for="attend-yes">Ya</label>
            </div>
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="attending" id="attend-no" value="No">
              <label class="form-check-label" for="attend-no">Tidak</label>
            </div>
          </div>
          
          <div class="mb-3" id="reason-container" style="display: none;">
            <label for="reason" class="form-label">Alasan Tidak Hadir</label>
            <textarea id="reason" class="form-control form-control-lg" rows="3" placeholder="Masukkan alasan jika tidak bisa hadir"></textarea>
          </div>
          
          <button type="submit" class="btn btn-rose btn-lg w-100">Kirim Konfirmasi</button>
        </form>
      </div>
    </div>
  </section>
  

  <!-- Footer -->
  <footer class="text-center">
    <p class="mb-0">&copy; 2025 Samuel & Oliv. All rights reserved.</p>
  </footer>

</div>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

<!-- Custom Script -->
<script>
// Menampilkan alasan jika pilih "Tidak Hadir"
document.querySelectorAll('input[name="attending"]').forEach((el) => {
  el.addEventListener('change', function() {
    if (document.getElementById('attend-no').checked) {
      document.getElementById('reason-container').style.display = 'block';
    } else {
      document.getElementById('reason-container').style.display = 'none';
    }
  });
});

// Handle submit form RSVP
document.getElementById('rsvp-form').addEventListener('submit', function(e) {
  e.preventDefault();

  const name = document.getElementById('name').value;
  const email = document.getElementById('email').value;
  const attending = document.querySelector('input[name="attending"]:checked').value;
  const reason = document.getElementById('reason').value;

  let message = `Nama: ${name}\nEmail: ${email}\nAkan Hadir: ${attending}`;
  
  if (attending === "No" && reason) {
    message += `\nAlasan Tidak Hadir: ${reason}`;
  }

  // Kirim ke WhatsApp
  const waMessage = encodeURIComponent(message);
  const waUrl = `https://wa.me/6281234567890?text=${waMessage}`;

  // Redirect ke WhatsApp
  window.open(waUrl, '_blank');
});


function openInvitation() {
  document.getElementById('opening').style.opacity = '0';
  setTimeout(() => {
    document.getElementById('opening').style.display = 'none';
    document.getElementById('main-content').style.display = 'block';
    document.getElementById('bgm').volume = 0;
    document.getElementById('bgm').play();
    fadeInMusic();
  }, 1000);
}

// Fade in music
function fadeInMusic() {
  var bgm = document.getElementById('bgm');
  var volume = 0;
  var interval = setInterval(function() {
    if (volume < 0.5) {
      volume += 0.01;
      bgm.volume = volume;
    } else {
      clearInterval(interval);
    }
  }, 100);
}

// Ambil nama tamu dari URL
window.onload = function() {
  const params = new URLSearchParams(window.location.search);
  const namaTamu = params.get('kepada');
  if (namaTamu) {
    document.getElementById('kepada-text').innerHTML = `Kepada Yth: <strong>${decodeURIComponent(namaTamu)}</strong>`;
  }
};

// Countdown
var countDownDate = new Date("April 30, 2025 10:00:00").getTime();
var x = setInterval(function() {
  var now = new Date().getTime();
  var distance = countDownDate - now;
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);
  document.getElementById("countdown").innerHTML = days + "d " + hours + "h "
  + minutes + "m " + seconds + "s ";
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("countdown").innerHTML = "Acara Sedang Berlangsung";
  }
}, 1000);
</script>

</body>
</html>
